# Generated by Django 3.2.6 on 2021-08-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demosubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=100)),
                ('a_email', models.CharField(max_length=100)),
                ('t_name', models.CharField(max_length=100)),
                ('t_url', models.CharField(max_length=100)),
                ('t_dis', models.TextField()),
            ],
        ),
    ]
