# Generated by Django 4.0.6 on 2022-07-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homescreenyt',
            name='s',
            field=models.TextField(default=''),
        ),
    ]
