# Generated by Django 3.2.8 on 2022-02-01 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_emaillist'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='emaillist',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
