# Generated by Django 4.0.6 on 2022-07-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_homescreenyt_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homescreenyt',
            name='s',
        ),
    ]
