# Generated by Django 3.2.7 on 2021-10-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Released',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('altImg', models.CharField(max_length=100)),
                ('albumart', models.ImageField(upload_to='albumArt')),
                ('sLink', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
